// Norwegian word list for the word chain game
// Common words, 2+ letters, lowercase, no special characters except æøå
export const NORWEGIAN_WORDS: string[] = [
  // A
  "alder", "alle", "allerede", "alltid", "andre", "annen", "annet",
  "arbeid", "arbeide", "arbeider", "aske", "avis", "avstand", "angrep", "ape",
  "arm", "auto", "akse", "aksel", "alen", "alene", "angst",
  "ansikt", "appelsin", "april", "areal", "art", "ate", "arv",
  "aksje", "aktiv", "alarm", "album", "alkohol", "alvor", "anbefale",
  "ande", "andel", "anelse", "angi", "anke", "ankomst", "anledning",
  "anlegg", "anmode", "anne", "annonsere", "ansette", "antall", "antenne",
  "anvende", "ape", "areal", "arena", "arke", "armband", "aroma",
  "arrest", "artig", "aske", "askim", "atferd", "atom", "atten",
  "atter", "august", "aure",
  // B
  "bak", "bakke", "ball", "bare", "barn", "base", "bedre", "begynne", "bein",
  "berg", "best", "bestemme", "bete", "bil", "bilde", "bit", "blad",
  "bli", "blid", "blikk", "blind", "blod", "blomst", "bok", "boks",
  "bolig", "bonde", "bord", "bore", "borg", "bort", "brann", "bred", "brev",
  "bro", "bror", "bruk", "bruke", "bryst", "bukk", "bukt", "bunn",
  "bur", "burde", "by", "bygge", "bytte", "bukse", "bue", "bugle",
  "bakeri", "balanse", "banan", "bank", "banke", "bar", "barber",
  "bark", "basse", "batteri", "bedrift", "befale", "begrave",
  "behandle", "behov", "bekrefte", "belgisk", "belte", "benk",
  "bensol", "berge", "beruse", "beskjed", "beskytte", "bestemor",
  "bestille", "bestige", "betale", "betong", "beundre", "bevege",
  "bibliotek", "bikke", "binne", "bjelle", "bjerk", "blande",
  "bleke", "blende", "blokk", "bluse", "blyant", "blære",
  "bonde", "bonde", "bonne", "booke", "borger", "borte", "bringe",
  "briste", "brist", "bruke", "brygge", "bryte", "bukke",
  "bulle", "bunke", "burre", "busk", "butikk",
  "bøk", "bøker", "bønne", "bøtte", "bøye", "bånd", "båt",
  // C
  "celle",
  // D
  "dag", "dale", "dame", "dans", "danse", "del", "dele", "dem", "den", "denne",
  "der", "dere", "det", "din", "disse", "ditt", "dra", "drakt", "drikke",
  "drive", "du", "due", "duk", "dum", "dusj", "dykke", "dyr", "dyrke",
  "damp", "data", "deg", "dekke", "delta", "denge", "depp",
  "dessert", "dikt", "dirke", "disk", "dokke", "dolk", "dom",
  "domine", "drage", "drama", "dress", "dritt", "dronning",
  "drukte", "drøm", "drømme", "duft", "dumme", "dunge", "dunke",
  "dust", "dvale", "dverg", "dyne", "dyp", "dyppe",
  "dør", "dårlig", "død", "døgn", "dømme", "døpe",
  // E
  "eddik", "egen", "egg", "eie", "eier", "eik", "ekte", "eksempel", "eld",
  "eller", "elske", "elv", "ende", "enda", "endre", "eneste", "enig", "enn",
  "er", "erfare", "ert", "eske", "evig", "esse",
  "edel", "effekt", "egenskap", "eksamen", "ekspert", "elegant",
  "element", "eliminere", "elite", "elendig", "elg", "emne",
  "energi", "engel", "engelsk", "enhet", "enke", "enkel",
  "enkelt", "enorm", "ense", "episode", "episk", "eple",
  "erfaring", "erklære", "erobre", "erte", "esel", "essens",
  "etasje", "eter", "etikett", "etter", "ettermiddag", "eventyr",
  // F
  "fag", "fakkel", "falle", "falsk", "fange", "far", "fare", "farge", "fart",
  "fast", "feil", "feire", "felt", "fem", "ferdig", "ferie", "fersk", "fest",
  "fett", "film", "fin", "finger", "finne", "fire", "fisk", "fiske", "fjell",
  "fjord", "flagg", "flamme", "flat", "flaske", "flink", "flokk", "flott",
  "fly", "flyge", "flykte", "flytte", "folk", "for", "foran", "forbi",
  "fore", "form", "fort", "fra", "fred", "fri", "frist", "frokost", "frost",
  "frukt", "full", "fugl", "funn", "furu", "fyr", "fylle",
  "fabrikk", "fad", "fager", "fakta", "falk", "fallskjerm",
  "farge", "farlig", "fase", "faste", "fat", "fattig", "favne",
  "feber", "fede", "feg", "feig", "fekte", "felle", "fellesskap",
  "femti", "fenomen", "ferge", "ferniss", "fest", "fiber",
  "fiende", "figur", "fiksere", "fille", "filosof", "filtre",
  "finesse", "firma", "fiske", "fjerne", "fjomp", "flekk",
  "flenge", "flette", "flis", "flis", "flopp", "flue",
  "flukt", "foss", "fotball", "fotspor", "frakk", "frakte",
  "framme", "frase", "frisk", "fritt", "frosne", "frue",
  "fyrig", "fyrste", "fysikk",
  "følge", "følge", "før", "først", "føle", "født", "få",
  // G
  "gal", "gammel", "gang", "ganske", "gave", "geit", "gi", "gift",
  "glad", "glass", "gli", "glo", "god", "godt", "grad", "gran", "grav", "grei",
  "grein", "grense", "gress", "gripe", "gris", "gro", "grop", "grov",
  "grunn", "gruppe", "gruve", "gul", "gull", "gutt", "gyldig",
  "garasje", "gard", "gardin", "garn", "gate", "gave", "geist",
  "gele", "geledd", "gemytt", "generell", "genser", "gest",
  "gilde", "gitar", "gjeld", "gjemme", "gjerde", "gjerne",
  "gjest", "gjette", "gjev", "gjort", "gjøre", "gjøk",
  "globe", "glorie", "gnaske", "gnist", "godbit", "godta",
  "golf", "gorilla", "grabb", "grafisk", "gram", "granite",
  "gras", "grav", "grense", "grep", "gresskar", "grill",
  "gripe", "grisk", "grop", "grotte", "gruble", "gruff",
  "gryte", "gråte", "grønn", "grøt",
  "gård", "gøy", "gå",
  // H
  "ha", "hage", "hai", "hakk", "halv", "ham", "hammer", "han", "handel",
  "hane", "hard", "hare", "hat", "hatt", "hav", "havre", "hei", "heks",
  "hel", "hele", "helle", "helst", "helt", "hende", "henne", "hennes", "her",
  "herde", "herre", "hest", "hete", "hilse", "himmel",  "hit",
  "hjelm", "hjelp", "hjem", "hjerne", "hjerte", "hjort", "hjul", "holde",
  "holt", "hoppe", "horn", "hos", "hud", "hull", "hund", "hundre", "hus",
  "huske", "hvem", "hver", "hverdag", "hvil", "hvis", "hvit",
  "hylle", "hytte", "hake", "hald", "hals", "halte",
  "hamle", "hamre", "hank", "harpe", "haste", "haug",
  "havne", "havn", "hekte", "helse", "helvete", "hemmelig",
  "henge", "hengi", "hente", "herav", "herje", "herlig",
  "herse", "heve", "hikke", "hilde", "hilsen", "hinke",
  "hint", "hirse", "historie", "hjemme", "hjemover", "hodet",
  "holder", "holme", "honning", "horisont", "hose", "hospits",
  "hotel", "hovmod", "hugge", "humle", "humor", "hurtig",
  "husly", "hval", "hveps", "hvile", "hvin", "hvirvel",
  "hybrid", "hygg", "hygge", "hyll", "hyse", "hysterisk",
  "høne", "høre", "høst", "høy", "hånd", "hår", "håpe",
  // I
  "ide", "ikke", "ild", "imot", "inne", "innen", "is", "ise",
  "idrett", "igle", "ikle", "ilbud", "ild", "ildsfare",
  "illustrere", "imaginere", "imitere", "import", "imponere",
  "indikere", "indre", "industri", "ingen", "innbo", "innbrud",
  "inneholde", "inngang", "innhold", "innsats", "innse",
  "insekt", "inspirere", "instruere", "intens", "interesse",
  // J
  "jage", "jakt", "jakke", "jamre", "januar", "jente", "jern", "jo", "jobb",
  "jobbe", "jord", "jul", "juni", "just",
  "jakke", "jambe", "jasmin", "jevn", "jodle", "jogge",
  "jordbær", "journalist", "jubel", "juble", "juice", "jumpe",
  "jungle", "junior", "jus", "justere", "juvel",
  // K
  "kaffe", "kai", "kake", "kald", "kall", "kalle", "kam", "kamp", "kan",
  "kanal", "kanne", "kant", "kapp", "kar", "kart", "kaste", "katt", "kind",
  "kirke", "kjede", "kjele", "kjempe", "kjenne", "kjerne", "kjole",
  "klar", "klare", "klasse", "kle", "klem",
  "klippe", "klokke", "kloss", "klubb", "klut", "knapp", "kne",
  "knekke", "kniv", "knopp", "knuse", "knute", "koble", "kode",
  "koke", "komme", "kone", "kontor", "konto", "kopp", "kork", "korn", "kort",
  "kost", "kraft", "krav", "krig", "krise", "kropp", "krus", "ku", "kul",
  "kule", "kunne", "kunst", "kurv", "kveld", "kyst",
  "kabinett", "kafe", "kakao", "kald", "kalender", "kamel",
  "kamera", "kamp", "kandidat", "kanin", "kapital", "kapsel",
  "karakter", "karosseri", "karriere", "kaste", "katalog",
  "kategori", "katt", "kjede", "kjeks", "kjelke", "kjenning",
  "kjetting", "kjole", "klinikk", "klokke", "klump", "knekk",
  "knele", "knirke", "knytte", "kokebok", "kolonne", "komfort",
  "komite", "kommune", "komplett", "konflikt", "konkret",
  "konsept", "konsert", "kontrakt", "kopiere", "koralrev",
  "korridor", "korrigere", "kortsiktig", "krabbe", "krage",
  "krakk", "krampe", "krans", "krasse", "kreft", "krem",
  "kremte", "krets", "krets", "kristall", "kritikk", "krok",
  "krone", "kronikk", "krukke", "krutt", "krydder", "kryss",
  "kryste", "kubbe", "kue", "kugle", "kuling", "kulp",
  "kultur", "kum", "kumme", "kunnskap", "kupp", "kur", "kurere",
  "kutt", "kutte", "kvalitet", "kvartal", "kvele", "kvern",
  "kvik", "kvise", "kviste",
  "kjøkken", "kjøpe", "kjøre", "kjøtt",
  // L
  "lag", "lage", "lake", "lam", "land", "lang", "langs", "langt", "lapp",
  "last", "lat", "latter", "lave", "led", "lede", "ledig", "lege", "legge",
  "leke", "lekk", "lenge", "leppe", "lese", "lest", "lett", "leve", "lide",
  "lik", "like", "likevel", "lille", "lime", "line", "linje", "list", "lite",
  "liten", "liv", "lov", "luft", "luke", "lukt", "lund", "lunge",
  "lure", "lurt", "lus", "lyd", "lykke", "lyn", "lys", "lyse",
  "lytte", "labb", "ladning", "lage", "lagre", "lakk", "lakris",
  "lamme", "lampe", "landlig", "landsbygg", "langsom",
  "lanterne", "lars", "larve", "laser", "laste", "latin",
  "latter", "laurbær", "lavine", "ledelse", "ledig", "ledd",
  "lefse", "legeme", "lego", "leie", "leire", "lekeplass",
  "leksjon", "lempe", "lenestol", "lenke", "lese", "levere",
  "lidenskap", "likestille", "lilje", "limousine", "lindre",
  "linse", "lirke", "liste", "liter", "litteratur", "livlig",
  "lodd", "logg", "logikk", "lokke", "lomme", "loppe",
  "losje", "losji", "love", "lufte", "lugge", "lukke", "luksus",
  "lumsk", "lunsj", "lure", "luske", "lut", "lykkes",
  "lære", "lærke", "løfte", "løk", "lønn", "løpe", "løs", "løse",
  "løve", "lås",
  // M
  "mage", "makt", "mal", "male", "man", "mange", "mann", "mark", "mat",
  "mate", "meg", "melde", "melk", "mellom", "men", "mene", "mengde",
  "mens", "mer", "merke", "mest", "min", "mine", "minne", "minst", "mitt",
  "miste", "mod", "mor", "morgen", "morsom", "mot", "mote", "motor",
  "mulig", "munn", "mur", "mus", "musikk", "myk", "mynt", "myr",
  "magi", "magisk", "mais", "makker", "makrelle", "maleri",
  "mamma", "mandel", "mandat", "mangle", "mappe", "marin",
  "marked", "marsjere", "maske", "maskin", "masse", "master",
  "materiell", "matrise", "matte", "med", "medbringe",
  "medisin", "medium", "megle", "mekle", "melde", "melon",
  "menneske", "mentor", "metall", "metode", "middag",
  "middel", "mild", "million", "mineraler", "ministere",
  "minus", "minutt", "misforstå", "misnøye", "miste",
  "mitraljøse", "mobbe", "modell", "moderne", "modifisere",
  "modig", "modul", "mogul", "molekyl", "moppe", "mord",
  "mosaikk", "moske", "motiv", "motstand", "motto", "mugge",
  "mulighet", "multi", "mumle", "munnstykke", "murstein",
  "muskel", "myke", "myndig", "mystisk",
  "mølle", "mørk", "mørke", "måke", "mål", "måle", "måne", "måte",
  // N
  "nabo", "naken", "natt", "natur", "nav", "navle", "ned", "negl",
  "nei", "nemlig", "nerve", "nese", "nest", "nett", "neve",
  "nikke", "niste", "noe", "noen", "nok", "nord", "norsk", "note", "null",
  "nummer", "ny", "nylig", "nytte",
  "nagle", "naiv", "nakke", "napp", "nasjon", "nasjonal",
  "natt", "naturlig", "navigere", "nedover", "nedre",
  "nedsatt", "negativ", "nekte", "nevne", "ni", "nikkel",
  "nitid", "nisse", "nivå", "node", "nodisk", "nonne",
  "nordisk", "norm", "nostalgi", "notat", "november",
  "nudler", "nulle", "nymfe", "nyre", "nysgjerrig",
  "nær", "nøkkel", "nøtt", "nål", "når",
  // O
  "odde", "oker", "okse", "olje", "ond", "onde", "onkel", "opp", "ord",
  "orden", "ork", "orm", "oss", "ost", "over", "ovn",
  "oboe", "observere", "offer", "offiser", "oliven", "ombord",
  "omsorg", "omtale", "omvei", "onsdag", "opera", "operere",
  "oppfinne", "oppgave", "opphav", "opphold", "oppleve",
  "oppmerksomhet", "opprette", "oppskrift", "oppsummere",
  "optisk", "orange", "ordbok", "ordne", "organisere",
  "orientere", "original", "orkan", "orre", "ose", "overse",
  "oversikt", "overvinne",
  // P
  "pakke", "panne", "par", "park", "part", "parti", "pass", "passe", "peke",
  "pels", "pen", "penge", "penger", "per", "perm", "person", "pine", "pipe",
  "plan", "plante", "plass", "plate", "plikt", "plog", "plomme",
  "poeng", "politi", "pose", "post", "potte", "pris", "problem",
  "puls", "pumpe", "punkt", "pust", "pute", "pynt",
  "padde", "pakke", "palass", "palle", "panel", "panikk",
  "pant", "papir", "par", "parade", "parfyme", "parti",
  "passasjer", "pause", "pave", "pedagogisk", "peile",
  "peis", "pekefinger", "pele", "pendel", "pensjon", "pepper",
  "perfekt", "periode", "perle", "pers", "pest", "pike",
  "pilar", "pilot", "pinne", "pirat", "piske", "plage",
  "planke", "plast", "plen", "plettfri", "plikt", "plukke",
  "plutselig", "pløye", "poesi", "polare", "politiker",
  "polo", "pompe", "populær", "porselen", "port", "portal",
  "portrett", "positiv", "potet", "praksis", "prakt", "prat",
  "prate", "predikant", "prege", "presse", "preste",
  "prestere", "prins", "prinsipp", "privat", "produsere",
  "profe", "program", "prosjekt", "protest", "pryd",
  "prøve", "pære", "pøl", "påske",
  // R
  "rad", "rage", "rak", "ramme", "rand", "rang", "rask", "raskt", "rase",
  "redd", "redde", "rede", "regel", "regn", "regne", "reise", "rekke", "rem",
  "ren", "renne", "rent", "rett", "rev", "rik", "rike", "ring", "ringe",
  "ris", "rise", "rist", "rive", "ro", "rolle", "rom", "rope", "rose", "rot",
  "rote", "ruin", "rull", "rulle", "rund", "runde", "rute",
  "rygg", "rykte",
  "rabalder", "rabatt", "radius", "raft", "rake", "ramle",
  "rampe", "rapport", "raps", "rar", "raseri", "rasle",
  "rast", "rav", "ravn", "reaksjon", "reagere", "realisere",
  "rebell", "redaksjon", "redigere", "refleks", "reform",
  "regnbue", "regnskap", "regjering", "regnskog",
  "reis", "reise", "rekord", "rektangel", "religion",
  "remse", "rengjøre", "rense", "reparere", "reprodusere",
  "resept", "reservere", "respekt", "rest", "resultat",
  "rette", "retning", "rettferdig", "revidere", "revolusjon",
  "rifle", "rigge", "rikdom", "rikelig", "rimelig", "ripe",
  "risikere", "risiko", "ritual", "rival", "rogn", "rokke",
  "roman", "romanse", "romme", "rops", "ror", "rosin",
  "rotte", "rovdyr", "rubrikk", "ruge", "rugge", "ruine",
  "rullestol", "rumle", "runde", "rusle", "rusk", "rust",
  "rå", "råd", "råde", "rødt", "røk", "røre", "røst",
  "røyk", "røyke",
  // S
  "sak", "salt", "same", "samle", "samling", "sammen", "sand", "sang",
  "sann", "se", "seg", "sei", "seil", "seile", "sein", "sekk",
  "selge", "selv", "sende", "seng", "senke", "senter", "sette", "side",
  "sikker", "sild", "sin", "sinne", "sist", "sitte", "sjel", "sju",
  "skade", "skaft", "skal", "skall", "skam", "skap", "skarp", "ski", "skift",
  "skifte", "skille", "skinne", "skip", "skive", "skog", "skole", "skrift",
  "skrike", "skrive", "skulder", "skulle", "sky", "skyld",
  "skylle", "slags", "slange", "slank", "slapp", "slekt", "slem", "slette",
  "slik", "slim", "slipe", "slippe", "slite", "slott", "sluke",
  "slukke", "slutt", "slutte", "smak", "smake", "smal", "smart",
  "smelte", "smile", "smitte", "snakke", "snart", "snill",
  "snitt", "snu", "sol", "som", "sommer", "sorg", "sort", "sove",
  "spark", "speil", "spenne", "spill", "spille", "spinne", "spise", "splitte",
  "spor", "sprette", "spring", "stake", "stall", "stamme", "stang", "stanse",
  "start", "sted", "steg", "stein", "steke", "stelle", "stemme", "stenge",
  "sterk", "still", "stille", "stiv", "stoff", "stol", "stoppe", "stor",
  "storm", "strand", "strek", "strid", "strikke", "stripe", "stue",
  "stund", "stykke", "styre", "styrke",
  "sukke", "sulte", "sum", "sunn", "sur", "svak", "svar", "svare", "svart",
  "sverd", "svette", "svin", "svinge",
  "sylte", "synge", "synke", "syre",
  "safari", "safran", "saft", "sagn", "saklig", "salat",
  "salong", "salve", "samarbeide", "samhold", "samtale",
  "samtid", "sandal", "sanksjone", "sannhet", "sanse",
  "sapiens", "satelitt", "scene", "seddel", "segel",
  "seier", "sekund", "selskap", "semester", "sentral",
  "september", "serie", "servere", "sesong", "signal",
  "silke", "simpel", "sirup", "situasjon", "sivil",
  "sjanse", "sjakk", "sjarm", "sjekke", "sjenere",
  "sjokolade", "sjåfør", "skade", "skaffe", "skalk",
  "skandale", "skapning", "skatt", "skikkelig", "skilt",
  "skinn", "skipper", "skisse", "skjebne", "skjerm",
  "skjorte", "skjule", "skjære", "slakke", "slanke",
  "slipe", "slipper", "slukte", "slurke", "sluse",
  "smerke", "smerte", "smilende", "smitte", "smugle",
  "smule", "snakke", "snappe", "snedig", "snekker",
  "snurre", "sokkel", "solle", "solrik", "sonde",
  "sortere", "sovne", "spalte", "spesial", "spiker",
  "spinne", "splint", "springe", "sprute", "spurve",
  "stampe", "standard", "stanse", "statue", "stave",
  "stearinlys", "steike", "stempel", "stenge", "steppe",
  "sterkt", "stete", "stikke", "stimulere", "stipend",
  "stolpe", "stram", "strategi", "streve", "struktur",
  "stubbe", "studere", "stupe", "styre", "styrte",
  "størkne", "størst", "støtte", "støv", "støy",
  "sår", "søke", "søle", "sønn", "sør", "søt", "søvn",
  "slå", "snø", "stå",
  // T
  "ta", "tak", "takk", "takke", "tale", "tall", "tang", "tanke", "tann",
  "tante", "tape", "tarm", "tau", "tavle", "tegn", "tegne", "telle", "telt",
  "tenke", "tenne", "tid", "tier", "tikke", "til", "tilbake", "time",
  "ting", "titt", "tjene", "tog", "tok", "toll", "tom", "tone", "topp", "torg",
  "torn", "tre", "treffe", "trekke", "trenge",
  "trist", "tro", "trolig", "tross", "trykk", "trykke",
  "tulle", "tung", "tur", "tull", "tusen", "tvil", "tvinge", "tyde",
  "tykk", "tynn", "type",
  "tabbe", "taffel", "tagge", "takle", "taksere", "takt",
  "talent", "taler", "tallerken", "tam", "tamp", "tanke",
  "tapper", "tarne", "taste", "tatovere", "teknisk",
  "telefon", "tema", "temperatur", "tempo", "tendens",
  "tenner", "teori", "teppe", "terapi", "term", "terreng",
  "terrier", "test", "teste", "tekst", "tekstil", "tigge",
  "tikke", "tilby", "tilgi", "tilstand", "tiltrekke",
  "timbre", "tinne", "tippe", "tirre", "tittel",
  "tjukke", "toalett", "tobe", "tolerere", "tolke",
  "tommel", "tomt", "topografi", "torget", "torne",
  "torpedo", "torsk", "total", "trafikk", "tragedie",
  "trakk", "tralle", "trampe", "transport", "trapp",
  "trass", "travel", "tredje", "treff", "trene", "treske",
  "tribunal", "trigger", "trille", "trio", "trives",
  "trofast", "troll", "tromme", "trone", "tropp",
  "trumf", "trussel", "trygg", "trøst", "trøste",
  "tulipan", "tumle", "tunnel", "turist", "turne",
  "turtleneck", "tvang", "tverr", "tvist", "tvungen",
  "tydelig", "tyfon", "tyggegummi", "tykne", "tynge",
  "typisk", "tyrann",
  "tøff", "tørke", "tørr", "tørst", "tåke", "tåle",
  "tår", "tåre", "tråd",
  // U
  "ugress", "uke", "ull", "ulv", "under", "ung", "unna", "urolig", "urt",
  "ute", "uten", "utgang", "utover",
  "ugle", "ulke", "ulme", "ultimat", "ultralyd", "umbra",
  "underholde", "underkjenne", "underlig", "understøtte",
  "undervise", "undre", "uniform", "unik", "univers",
  "unktig", "unnskyld", "unngå", "unntak", "uoverensstemmelse",
  "urede", "urmaker", "urokke", "urte", "usann", "usikker",
  "ussel", "ustabil", "usynlig", "utbe", "utbre",
  "utdanne", "utdeling", "utdype", "utfall", "utflukt",
  "utforme", "utfordre", "utgi", "utgjøre", "utheve",
  "utholde", "utlede", "utlending", "utligne", "utmerke",
  "utrydde", "utsette", "utside", "utsikt", "utslipp",
  "utstille", "utstyre", "uttale", "uttrykk", "utvalg",
  "utvide", "utvikle",
  // V
  "vakker", "vakle", "vakt", "valg", "vann", "vant", "var", "vare", "varm",
  "varme", "varsel", "vaske", "ved", "vei", "veie", "vekke", "vekst", "vel",
  "velge", "vende", "venn", "venne", "vente", "verd", "verdi",
  "verk", "verst", "vest", "videre", "vilje", "vill", "ville",
  "vind", "vindu", "vinge", "vinne", "vinter", "virke", "vis",
  "vise", "viss", "vite", "vokse", "vold", "vondt", "vri", "vugge", "vurdere",
  "vakle", "vaksinere", "valfart", "vandre", "vanlig",
  "vanske", "varde", "variere", "varsle", "vase",
  "vegg", "veksel", "velkomst", "vende", "vennlig",
  "ventil", "veranda", "verdifull", "verge", "verifisere",
  "vers", "versjon", "verst", "verve", "vesle", "vestre",
  "vifte", "viktig", "viking", "vilt", "vinglass",
  "virkelig", "virtuell", "virus", "visdom", "visitt",
  "visuell", "vitamin", "vokal", "voksen", "volt",
  "vugge", "vulkan",
  "vår", "våge", "våken", "våpen", "vått",
  // Y
  "yde", "ynde", "yre", "yrke", "ytre",
  "yoghurt", "yppe",
  // Æ
  "ære", "ærlig", "ærfull",
  // Ø
  "øke", "øl", "ønske", "øre", "ørn", "øse", "øst", "øve", "øy", "øye",
  "ødelegge", "økonomi", "ørken", "ørliten", "østlig", "øvelse", "øyeblikk",
  // Å
  "åker", "ånd", "åpen", "år", "åre", "årsak", "årstid", "åtte",
  "åpne", "åpning", "årvåken",
];
